
Convert: Main.o parsing.o convert.o Length.o Amount.o Angle.o Area.o Data.o Electric_charge.o Energy.o Frequency.o Mass.o Power.o Pression.o QuantityOfSubstance.o Speed.o Strength.o Temperature.o Time.o selectionswitchAmount.o selectionswitchAngle.o selectionswitchData.o selectionswitchEnergy.o selectionswitchFrequency.o selectionswitchLength.o selectionswitchMass.o selectionswitchPower.o selectionswitchPression.o selectionswitchQuantityOfSubstance.o selectionswitchSpeed.o selectionswitchTemperature.o selectionswitchTime.o 
		gcc -o Convert -lm Main.o parsing.o convert.o Length.o Amount.o Angle.o Area.o Data.o Electric_charge.o Energy.o Frequency.o Mass.o Power.o Pression.o QuantityOfSubstance.o Speed.o Strength.o Temperature.o Time.o selectionswitchAmount.o selectionswitchAngle.o selectionswitchData.o selectionswitchEnergy.o selectionswitchFrequency.o selectionswitchLength.o selectionswitchMass.o selectionswitchPower.o selectionswitchPression.o selectionswitchQuantityOfSubstance.o selectionswitchSpeed.o selectionswitchTemperature.o selectionswitchTime.o 
 
Main.o: Main.c
		gcc -c Main.c
 		
parsing.o: Service/parsing.c
		gcc -c Service/parsing.c

convert.o: Service/convert.c
		gcc -c Service/convert.c

Length.o: Modules/Length.c
		gcc -c Modules/Length.c

Amount.o: Modules/Amount.c
		gcc -c Modules/Amount.c
		
Angle.o: Modules/Angle.c
		gcc -c Modules/Angle.c
		
Area.o: Modules/Area.c
		gcc -c Modules/Area.c

Data.o: Modules/Data.c
		gcc -c Modules/Data.c
		
Electric_charge.o: Modules/Electric_charge.c
		gcc -c Modules/Electric_charge.c
	
Energy.o: Modules/Energy.c
		gcc -c Modules/Energy.c
		
Frequency.o: Modules/Frequency.c
		gcc -c Modules/Frequency.c
		
Mass.o: Modules/Mass.c
		gcc -c Modules/Mass.c
		
Power.o: Modules/Power.c
		gcc -c Modules/Power.c
		
Pression.o: Modules/Pression.c
		gcc -c Modules/Pression.c
		
QuantityOfSubstance.o: Modules/QuantityOfSubstance.c
		gcc -c Modules/QuantityOfSubstance.c

Speed.o: Modules/Speed.c
		gcc -c Modules/Speed.c
		
Strength.o: Modules/Strength.c
		gcc -c Modules/Strength.c
		
Temperature.o: Modules/Temperature.c
		gcc -c Modules/Temperature.c
		
Time.o: Modules/Time.c
		gcc -c Modules/Time.c
		
selectionswitchAmount.o: Switches/selectionswitchAmount.c
		gcc -c Switches/selectionswitchAmount.c

selectionswitchAngle.o: Switches/selectionswitchAngle.c
		gcc -c Switches/selectionswitchAngle.c
		
selectionswitchData.o: Switches/selectionswitchData.c
		gcc -c Switches/selectionswitchData.c

selectionswitchEnergy.o: Switches/selectionswitchEnergy.c
		gcc -c Switches/selectionswitchEnergy.c
		
selectionswitchFrequency.o: Switches/selectionswitchFrequency.c
		gcc -c Switches/selectionswitchFrequency.c

selectionswitchLength.o: Switches/selectionswitchLength.c
		gcc -c Switches/selectionswitchLength.c
		
selectionswitchMass.o: Switches/selectionswitchMass.c
		gcc -c Switches/selectionswitchMass.c

selectionswitchPower.o: Switches/selectionswitchPower.c
		gcc -c Switches/selectionswitchPower.c
		
selectionswitchPression.o: Switches/selectionswitchPression.c
		gcc -c Switches/selectionswitchPression.c

selectionswitchQuantityOfSubstance.o: Switches/selectionswitchQuantityOfSubstance.c
		gcc -c Switches/selectionswitchQuantityOfSubstance.c
		
selectionswitchSpeed.o: Switches/selectionswitchSpeed.c
		gcc -c Switches/selectionswitchSpeed.c

selectionswitchTemperature.o: Switches/selectionswitchTemperature.c
		gcc -c Switches/selectionswitchTemperature.c
		
selectionswitchTime.o: Switches/selectionswitchTime.c
		gcc -c Switches/selectionswitchTime.c
